Create a vector (array) of 1XN dimension representing N-
dimensional feature vector of a sample. Write a program to

compute the mean and variance of the elements present in the
array.

In [1]:
import numpy as np

def compute_mean_and_variance(vector):
    mean = np.mean(vector)
    variance = np.var(vector)
    return mean, variance

N = 10
vector = np.random.rand(N)

mean, variance = compute_mean_and_variance(vector)
print("Vector (1xN):", vector)
print("Mean of the vector:", mean)
print("Variance of the vector:", variance)

Vector (1xN): [0.60764553 0.25989763 0.73391513 0.47923264 0.78910299 0.82202654
 0.30862357 0.80785072 0.81174345 0.84477364]
Mean of the vector: 0.6464811830679551
Variance of the vector: 0.04445483792755442


Create two vectors each of dimension 1XM each representing N- dimensional feature vector of a sample. Write a program to

compute the Covariance between them.

In [2]:
import numpy as np
def covarience(vector1,vector2):
    cov=np.cov(vector1,vector2)
    return cov
N = 5
vector1 = np.random.rand(N)
vector2 = np.random.rand(N)
cov=covarience(vector1,vector2)
print("Vector 1:", vector1)
print("Vector 2:", vector2)
print(cov)

Vector 1: [0.93471116 0.84515048 0.6708491  0.43377344 0.57246477]
Vector 2: [0.93379476 0.94309057 0.48188555 0.40550786 0.94718273]
[[0.04094473 0.03630376]
 [0.03630376 0.07505217]]


Create two vectors each of dimension 1XN. Write a program to compute the Correlation between them.

In [3]:
import numpy as np
def correlation(vector1,vector2):
    corr=np.corrcoef(vector1,vector2)
    return corr
N = 5
vector1= np.random.rand(N)
vector2= np.random.rand(N)
corr=correlation(vector1,vector2)
print("Vector 1:", vector1)
print("Vector 2:", vector2)
print(corr)

Vector 1: [0.89682917 0.13281416 0.27951511 0.53423796 0.03847826]
Vector 2: [0.52509783 0.44821022 0.11314973 0.91029774 0.93084634]
[[ 1.         -0.03722685]
 [-0.03722685  1.        ]]


Create a Matrix of MXN dimension representing the M-dimensional feature vector for N number of samples i. e (i,j)th entry of the matrix represents the ith feature of jth sample. Write a program to compute the covariance matrix and correlation matrix. Comment on takeaways from these matrixes.

In [4]:
import numpy as np
M = 5
N = 3
matrix = np.random.rand(M,N)
cov_matrix = np.cov(matrix)
corr_matrix = np.corrcoef(matrix)
print("Matrix (MXN):", matrix)
print("Covariance Matrix:")
print(cov_matrix)
print("Correlation Matrix:")
print(corr_matrix)


Matrix (MXN): [[0.32309081 0.02188393 0.24323162]
 [0.53432503 0.68492475 0.08914442]
 [0.77059517 0.11615685 0.49615725]
 [0.76488089 0.46061627 0.26465415]
 [0.61061606 0.03585182 0.17218438]]
Covariance Matrix:
[[ 0.02434965 -0.02361409  0.05052499  0.01470309  0.03971877]
 [-0.02361409  0.09597004 -0.03379676  0.04893658  0.00456628]
 [ 0.05052499 -0.03379676  0.108001    0.04365632  0.09137941]
 [ 0.01470309  0.04893658  0.04365632  0.06353415  0.06124661]
 [ 0.03971877  0.00456628  0.09137941  0.06124661  0.09019381]]
Correlation Matrix:
[[ 1.         -0.48849145  0.98524901  0.37381665  0.84754183]
 [-0.48849145  1.         -0.3319658   0.62670351  0.04908023]
 [ 0.98524901 -0.3319658   1.          0.52702307  0.92586165]
 [ 0.37381665  0.62670351  0.52702307  1.          0.80907742]
 [ 0.84754183  0.04908023  0.92586165  0.80907742  1.        ]]
